version: "3.9"

services:
  backend:
    build: .
    container_name: feedback-backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - JWT_SECRET=supersecret
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:6
    container_name: feedback-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
